spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres

#発行したSQLをログに出力する設定
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE